---
# The Playbook is for getting data from Node
- hosts: slave4
  user: ubuntu
  vars_files: var.yaml

  become: yes
  become_method: sudo
  tasks:

#  - debug:
#      msg: System {{ github_user }}  {{ app_name }} {{ ansible_ssh_user }}

  - name: Execute the shell Script
    shell: bash /home/{{ ansible_ssh_user }}/{{ app_name }}/collect-data.sh

  - name: zip a collect folder
    shell: sudo tar -zcvf "$(hostname).tar.gz" collect/

  - name: fetch system data of Node
    fetch:
      src: "{{ hname.stdout }}.tar.gz"
#      src: ip-172-31-19-141.tar.gz
      dest: "/home/{{ansible_ssh_user}}/new_zip/"
      flat: yes

  - name: cleaning up folders
    shell: sudo rm -rf collect/

  - name: cleaning up zips
    shell: sudo rm -rf "{{ hname.stdout }}.tar.gz"