---
# Install system apt packages
- hosts: slave4
  vars:
    ansible_python_interpreter: /usr/bin/python3
    github_user: sagarg1988
    app_name: Ansible-Rollback-Script
    ansible_ssh_user: ubuntu
  become: yes
  become_method: sudo
  tasks:
  - name: clone repo
    git:
      repo: 'https://github.com/{{ github_user }}/{{ app_name }}.git'
      dest: /home/{{ ansible_ssh_user }}/{{ app_name }}
      update: yes  # Does a git pull if the repo already exists
      clone: yes

  - name: Ensure boto and boto3 modules are installed
    pip:
      name: "{{ item }}"
    with_items:
      - boto3
      - botocore

  - name: Execute the shell Script
    shell: bash /home/{{ ansible_ssh_user }}/{{ app_name }}/collect-data.sh

  - name: Get Hostname of Node
    shell: hostname
    register: hostname_output
  - debug: msg="{{ hostname_output.stdout }}"

  - name: zip a collect folder
    shell: sudo tar -zcvf "{{hostname_output}}".tar.gz /home/ubuntu/collect/
#
  - name: upload data import file
    aws_s3:
      bucket: hsbcbucketdilshad
      aws_access_key: ""
      aws_secret_key: ""
      object: collect1
      src: /home/ubuntu/collect.tar.gz
      mode: put