---
# Install system apt packages
- hosts: slave4
  vars:
    ansible_python_interpreter: /usr/bin/python3
    github_user: sagarg1988
    app_name: Ansible-Rollback-Script
    ansible_ssh_user: ubuntu
  become: yes
  become_method: sudo
  tasks:
  - name: clone repo
    git:
      repo: 'https://github.com/{{ github_user }}/{{ app_name }}.git'
      dest: /home/{{ ansible_ssh_user }}/{{ app_name }}
      update: yes  # Does a git pull if the repo already exists
      clone: yes

  - name: Execute the shell Script
    shell: bash /home/{{ ansible_ssh_user }}/{{ app_name }}/collect-data.sh

  - name: zip a collect folder
    shell: sudo tar -zcvf "$(hostname).tar.gz" collect/

  - name: copy zip files to central location
    shell: scp my_file.txt  ubuntu@3.129.61.24:~/zipfiles