---
# Install system apt packages
- hosts: slave4
  vars:
    ansible_python_interpreter: /usr/bin/python3
    github_user: sagarg1988
    app_name: Ansible-Rollback-Script
    ansible_ssh_user: ubuntu
  become: yes
  become_method: sudo
  tasks:
  - name: get AWS_ACCESS_KEY_ID
    shell: echo ${AWS_ACCESS_KEY_ID}
    register: mykey

  - name: get AWS_SECRET_ACCESS_KEY
    shell: echo ${AWS_SECRET_ACCESS_KEY}
    register: mysecret
  - name: clone repo
#    debugger: on_failed
    git:
      repo: 'https://github.com/{{ github_user }}/{{ app_name }}.git'
      dest: /home/{{ ansible_ssh_user }}/{{ app_name }}
      update: yes  # Does a git pull if the repo already exists
      clone: yes

#  - name: install virtualenv
#    pip:
#      name: virtualenv
#      executable: pip3
#    become: yes
#    become_user: root
#
  - name: Ensure boto and boto3 modules are installed
    pip:
      name: "{{ item }}"
    with_items:
      - boto3
      - botocore
#  - name: install modules in a virtualenv
#    pip:
#      requirements: /home/{{ ansible_ssh_user }}/{{ app_name }}/requirements.txt
#      virtualenv: /home/{{ ansible_ssh_user }}/{{ app_name }}/env
#      virtualenv_python: python3.6

  - name: upload data import file
    aws_s3:
      bucket: hsbcbucketdilshad
#      aws_access_key: "{{ mykey.stdout }}"
#      aws_secret_key: "{{ mysecret.stdout }}"
#      object: home/ubuntu/my_file.txt
      src: home/ubuntu/my_file.txt
      mode: put

#   s3: aws_access_key={{ mykey.stdout }} aws_secret_key={{ mysecret.stdout }} bucket=hsbcbucketdilshad object=/home/ubuntu/print.py mode=put
#    s3:
#     aws_access_key: "{{ mykey.stdout }}"
#     aws_secret_key: "{{ mysecret.stdout }}"
#     bucket: hsbcbucketdilshad
#     object: /home/ubuntu/my_file.txt
#     src: /home/ubuntu/my_file.txt
#     mode: put
#    s3_bucket:
#     aws_access_key: "{{ mykey.stdout }}"
#     aws_secret_key: "{{ mysecret.stdout }}"
#     bucket: hsbcbucketdilshad
#     object: /home/ubuntu/my_file.txt
#     src: /home/ubuntu/my_file.txt
#     mode: put
