---
# The Playbook is for getting data from Node
- hosts: slave4
  user: ubuntu
  vars:
    ansible_python_interpreter: /usr/bin/python3
    github_user: sagarg1988
    app_name: Ansible-Rollback-Script
    ansible_ssh_user: ubuntu
  become: yes
  become_method: sudo
  tasks:
  - name: clone repo
    git:
      repo: 'https://github.com/{{ github_user }}/{{ app_name }}.git'
      dest: /home/{{ ansible_ssh_user }}/{{ app_name }}
      update: yes  # Does a git pull if the repo already exists
      clone: yes

  - name: get Hostname:
    shell: hostname
    register: hname

  - name: Print mosh version
    debug: msg="Hostname: {{ hname.stdout }}"

  - name: Execute the shell Script
    shell: bash /home/{{ ansible_ssh_user }}/{{ app_name }}/collect-data.sh

  - name: zip a collect folder
    shell: sudo tar -zcvf "$(hostname).tar.gz" collect/

  - name: fetch system data of Node
    fetch:
      src: ip-172-31-19-141.tar.gz
      dest: /home/ubuntu/new_zip/
      flat: yes

  - name: cleaning up
    shell: sudo rm -rf collect/
