---
# Install system apt packages
- hosts: slave4
  become: yes
  become_method: sudo
  tasks:
  - name: get AWS_ACCESS_KEY_ID
    local_action: shell echo ${AWS_ACCESS_KEY_ID}
    register: mykey

  - name: get AWS_SECRET_ACCESS_KEY
    local_action: shell echo ${AWS_SECRET_ACCESS_KEY}
    register: mysecret

  - name: upload data import file
#    s3: aws_access_key={{ mykey.stdout }} aws_secret_key={{ mysecret.stdout }} bucket=hsbcbucketdilshad object=/home/ubuntu/print.py mode=put
#    s3:
#     aws_access_key: "{{ mykey.stdout }}"
#     aws_secret_key: "{{ mysecret.stdout }}"
#     bucket: hsbcbucketdilshad
#     object: /home/ubuntu/my_file.txt
#     src: /home/ubuntu/my_file.txt
#     mode: put
#    s3_bucket:
#     aws_access_key: "{{ mykey.stdout }}"
#     aws_secret_key: "{{ mysecret.stdout }}"
#     bucket: hsbcbucketdilshad
#     object: /home/ubuntu/my_file.txt
#     src: /home/ubuntu/my_file.txt
#     mode: put

    aws_s3:
      bucket: hsbcbucketdilshad
      object: home/ubuntu/my_file.txt
      src: home/ubuntu/my_file.txt
      mode: put