---
# Install system apt packages
- hosts: slave4
  vars:
    ansible_python_interpreter: /usr/bin/python3
    github_user: sagarg1988
    app_name: Ansible-Rollback-Script
    ansible_ssh_user: ubuntu
  become: yes
  become_method: sudo
  tasks:
  - name: clone repo
    git:
      repo: 'https://github.com/{{ github_user }}/{{ app_name }}.git'
      dest: /home/{{ ansible_ssh_user }}/{{ app_name }}
      update: yes  # Does a git pull if the repo already exists
      clone: yes
  - name: copy files to remote location
    copy:
      src: $HOME/sagar.py
      remote_src: true
      dest: $HOME/sagar_copy.py
#  - name:  Synchronization using rsync protocol on delegate host (push)
#    synchronize:
#      src: /home/ubuntu/Ansible-Rollback-Script/files/sagar.py
#      dest: rsync://3.129.61.24/
##    delegate_to: delegate.host