---
- hosts: slave4
  become: yes
  become_method: sudo

  tasks:
      - name: Copy bash script
        shell: sudo cp /home/ubuntu/Ansible-Rollback-Script/collect-data.sh /home/ubuntu/

    - name: Execute the shell Script
      shell: bash collect-data.sh

#    - name: activate environmane
#      shell: source /home/ubuntu/hsbc_env

    - name: Upload the files to centralised location
      shell: python upload.py
