---
# Install system apt packages
- hosts: slave4
  become: yes
  become_method: sudo
  tasks:
  - name: install packages
    apt: name={{item}} state=present
    with_items:
      - python-pip   # Optional
      - python-dev   # Optional
      - python3-pip
      - python3-dev

# Install the app, note: don't do these tasks with become sudo
- hosts: slave4
  vars:
    github_user: sagarg1988
    app_name: Ansible-Rollback-Script
    ansible_ssh_user: ubuntu
  tasks:
  - name: clone repo
    debugger: on_failed
    git:
      repo: 'https://github.com/{{ github_user }}/{{ app_name }}.git'
      dest: /home/{{ ansible_ssh_user }}/{{ app_name }}
      update: yes  # Does a git pull if the repo already exists
#      clone: yes
  - name: install virtualenv
    pip:
      name: virtualenv
      executable: pip3
    become: yes
    become_user: root
  - name: install modules in a virtualenv
    pip:
      requirements: /home/{{ ansible_ssh_user }}/{{ app_name }}/requirements.txt
      virtualenv: /home/{{ ansible_ssh_user }}/{{ app_name }}/env
      virtualenv_python: python3.5

#  - name: Execute the shell Script
#    shell: bash /home/{{ ansible_ssh_user }}/{{ app_name }}/collect-data.sh

  - name: Execute the Script
    shell: python upload.py
