---
- hosts: slave1
#  user: ubuntu
  become: yes
  become_method: sudo

  tasks:
    - name: Install add-apt-repostory
      become: yes
      apt: name=software-properties-common state=latest

    - name: Add Oracle Java Repository
      become: yes
      apt_repository: repo='ppa:webupd8team/java'

    - name: Accept Java 8 License
      become: yes
      debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

    - name: Install Oracle Java 8
      become: yes
      apt: name={{item}} state=present
      with_items:
        - openjdk-8-jre-headless
        - ca-certificates
#        - oracle-java8-set-default

    - name: Java Service Check
      shell: java -version
      register: check_java
      ignore_errors: True
      changed_when: False

    - name: Print java_install
      debug:
        msg: "Java: {{ check_java }}"