---
- hosts: slave1
#  user: ubuntu
  become: yes
  become_method: sudo

  tasks:
    - name: Installing Java 11
      vars:
        latest_version: '11'
      become: yes
      apt:
        name:
          - openjdk-111-jre-headless
          - ca-certificates
        state: present
      register: java_status
      ignore_errors: True
      failed_when: "'FAILED' in java_status"


    - name: java verion status
      set_fact:
        installation_status: 'FAIL'
        when: "'FAILED' in java_status"

    - name: print variable
      debug:
        msg: "{{ installation_status}}"

    - name: Install add-apt-repostory
      become: yes
      apt: name=software-properties-common state=latest

    - name: Add Oracle Java Repository
      become: yes
      apt_repository: repo='ppa:webupd8team/java'

    - name: Accept Java 8 License
      become: yes
      debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

    - name: Install Oracle Java 8
      become: yes
      apt: name={{item}} state=present
      with_items:
        - openjdk-8-jre-headless
        - ca-certificates
      when: "installation_status == 'FAIL'"
#
    - name: Java Installed version Check
      shell: java -version 2>&1 |awk 'NR==1{ gsub(/"/,""); print $3 }'
      register: check_java
      ignore_errors: True
      changed_when: False

    - name: Store Java version
      set_fact:
        java_version: "{{ '.'.join((check_java.stdout.split('.')[0], check_java.stdout.split('.')[1]))|float }}"

    - name: Print java_install
      debug:
        msg: "{{ java_version }}"

    - name: Print java_install
      debug:
        msg: "{{ '11' >= java_version  }}"



#    - name: Checking Latest version of Java
#      shell: java -version 2>&1 |awk 'NR==1{ gsub(/"/,""); print $3 }'
#      register: check_java
#      ignore_errors: True
#      changed_when: False
#
#    - name: Store Java version
#      set_fact:
#        java_version: "{{ '.'.join((check_java.stdout.split('.')[0], check_java.stdout.split('.')[1]))|float }}"
#
#    - name: Print java_install
#      debug:
#        msg: "{{ java_version }}"