---
- hosts: slave1
#  user: ubuntu
  become: yes
  become_method: sudo

  tasks:
    - name: Get the list of upgraded packages
      shell: awk '$3=="upgrade"' /var/log/dpkg.log | awk '{print $4}'
      register: lib_list
      ignore_errors: True
      changed_when: False

#    - name: Print the list
#      debug:
#        msg: "{{ lib_list.stdout_lines }}"

    - name: Print the array
      debug:
        msg: "{{ item }}"
      with_items:
        - "{{ lib_list }}"

